Date/Time: 3/2/2020 3:28:22 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID) in C:\Vatebra Projects\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 97

Date/Time: 3/2/2020 3:49:58 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID) in C:\Vatebra Projects\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 97

Date/Time: 3/2/2020 3:56:50 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID) in C:\Vatebra Projects\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 97

Date/Time: 3/2/2020 4:04:31 PM
Error message: Access to the path 'C:\1' is denied.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID) in C:\Vatebra Projects\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 128

Date/Time: 3/2/2020 4:41:16 PM
Error message: Access to the path 'C:\Vatebra Projects\CEMIS\CEMIS.Web.CentralPortal\wwwroot\StudentPhotos\1' is denied.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID) in C:\Vatebra Projects\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 210

Date/Time: 3/2/2020 5:10:25 PM
Error message: Access to the path 'C:\Vatebra Projects\CEMIS\CEMIS.Web.CentralPortal\wwwroot\StudentPhotos\1\jhgjhghj.jpg' is denied.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID) in C:\Vatebra Projects\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 210

Date/Time: 3/2/2020 5:12:36 PM
Error message: Access to the path 'C:\Vatebra Projects\CEMIS\CEMIS.Web.CentralPortal\wwwroot\StudentPhotos\1\jhgjhghj.jpg' is denied.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID) in C:\Vatebra Projects\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 210

Date/Time: 3/2/2020 5:15:45 PM
Error message: Access to the path 'C:\Vatebra Projects\CEMIS\CEMIS.Web.CentralPortal\wwwroot\StudentPhotos\1\jhgjhghj.jpg' is denied.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID) in C:\Vatebra Projects\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 210

Date/Time: 3/2/2020 5:20:58 PM
Error message: Access to the path 'C:\Vatebra Projects\CEMIS\CEMIS.Web.CentralPortal\wwwroot\StudentPhotos\1\jhgjhghj.jpg' is denied.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID) in C:\Vatebra Projects\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 210

Date/Time: 3/2/2020 5:24:24 PM
Error message: Access to the path 'C:\Vatebra Projects\CEMIS\CEMIS.Web.CentralPortal\wwwroot\StudentPhotos\1\jhgjhghj.jpg' is denied.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID)

Date/Time: 3/2/2020 5:27:19 PM
Error message: Access to the path 'C:\Vatebra Projects\CEMIS\CEMIS.Web.CentralPortal\wwwroot\StudentPhotos\1\jhgjhghj.jpg' is denied.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID)

Date/Time: 3/2/2020 5:31:20 PM
Error message: Access to the path 'C:\Vatebra Projects\CEMIS\CEMIS.Web.CentralPortal\wwwroot\StudentPhotos\1\jhgjhghj.jpg' is denied.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID)

Date/Time: 3/2/2020 5:49:27 PM
Error message: Access to the path 'C:\Vatebra Projects\CEMIS\CEMIS.Web.CentralPortal\wwwroot\StudentPhotos\1\jhgjhghj.jpg' is denied.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Cemis.Business.Central.Repository.StudentRepository.PushStudentDetails(StudentViewModel studentVM, Int64 collegeID) in C:\Vatebra Projects\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 210

Date/Time: 3/31/2020 2:10:09 PM
Error message: The process cannot access the file 'C:\Users\aolatunji\Documents\Azure\CEMIS\CEMIS.Web.CentralPortal\wwwroot\CetificateUploads\2\00000000-0000-0000-0000-000000000000Shool cert' because it is being used by another process.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 150

Date/Time: 3/31/2020 2:09:46 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 166

Date/Time: 3/31/2020 2:10:10 PM
Error message: The process cannot access the file 'C:\Users\aolatunji\Documents\Azure\CEMIS\CEMIS.Web.CentralPortal\wwwroot\CetificateUploads\2\00000000-0000-0000-0000-000000000000Shool cert' because it is being used by another process.
Inner exception: 
Stack trace:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 150

Date/Time: 3/31/2020 2:10:23 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 166

Date/Time: 4/1/2020 3:56:02 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 178

Date/Time: 4/1/2020 3:56:03 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 178

Date/Time: 4/1/2020 3:56:04 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 178

Date/Time: 4/1/2020 3:54:34 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 178

Date/Time: 4/1/2020 3:56:06 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 178

Date/Time: 4/2/2020 7:00:18 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 178

Date/Time: 4/3/2020 1:12:56 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 178

Date/Time: 4/7/2020 2:14:13 PM
Error message: Cannot create a DbSet for 'AcademicSession' because this type is not included in the model for the context.
Inner exception: 
Stack trace:    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at CEMIS.Business.Central.Repository.CollegeRepository.SessionInformtion(AcademicSessionViewModel sessionVM, College college) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\CollegeRepository.cs:line 347

Date/Time: 4/27/2020 3:56:51 AM
Error message: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'appContextCentral'.
Inner exception: 
Stack trace:    at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at CEMIS.Business.Central.Repository.Repository`1.CreateAsync(TObject TObject) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\Repository.cs:line 73
   at Cemis.Business.Central.Repository.ActivityLogRepository.CreateActivityLog(String descriptn, String moduleName, String moduleAction, Int64 userid, Object record, String IPAddress) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\ActivityLogRepository.cs:line 36

Date/Time: 4/27/2020 3:57:15 AM
Error message: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'appContextCentral'.
Inner exception: 
Stack trace:    at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at CEMIS.Business.Central.Repository.Repository`1.CreateAsync(TObject TObject) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\Repository.cs:line 73
   at Cemis.Business.Central.Repository.ActivityLogRepository.CreateActivityLog(String descriptn, String moduleName, String moduleAction, Int64 userid, Object record, String IPAddress) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\ActivityLogRepository.cs:line 36

Date/Time: 4/27/2020 3:57:23 AM
Error message: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'appContextCentral'.
Inner exception: 
Stack trace:    at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at CEMIS.Business.Central.Repository.Repository`1.CreateAsync(TObject TObject) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\Repository.cs:line 73
   at Cemis.Business.Central.Repository.ActivityLogRepository.CreateActivityLog(String descriptn, String moduleName, String moduleAction, Int64 userid, Object record, String IPAddress) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\ActivityLogRepository.cs:line 36

Date/Time: 4/27/2020 5:05:43 AM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Web.CentralPortal.UserController.Userupdate(UsersObject model) in C:\Users\aolatunji\Documents\Azure\CEMIS\CEMIS.Web.CentralPortal\Controllers\UserController.cs:line 226

Date/Time: 4/28/2020 10:06:18 AM
Error message: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'appContextCentral'.
Inner exception: 
Stack trace:    at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at CEMIS.Business.Central.Repository.Repository`1.CreateAsync(TObject TObject) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\Repository.cs:line 73
   at Cemis.Business.Central.Repository.ActivityLogRepository.CreateActivityLog(String descriptn, String moduleName, String moduleAction, Int64 userid, Object record, String IPAddress) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\ActivityLogRepository.cs:line 36

Date/Time: 4/28/2020 6:36:18 PM
Error message: Value cannot be null.
Parameter name: entity
Inner exception: 
Stack trace:    at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at CEMIS.Business.Central.Repository.Repository`1.Create(TObject TObject) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\Repository.cs:line 94
   at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 274

Date/Time: 4/28/2020 6:36:32 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 156

Date/Time: 4/28/2020 6:40:25 PM
Error message: Value cannot be null.
Parameter name: entity
Inner exception: 
Stack trace:    at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at CEMIS.Business.Central.Repository.Repository`1.Create(TObject TObject) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\Repository.cs:line 94
   at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 274

Date/Time: 4/28/2020 6:40:35 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 156

Date/Time: 4/28/2020 6:46:05 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 156

Date/Time: 4/28/2020 7:00:16 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 157

Date/Time: 4/28/2020 7:00:52 PM
Error message: Object reference not set to an instance of an object.
Inner exception: 
Stack trace:    at CEMIS.Business.Central.Repository.StaffRepository.PushCollegeStaff(CollegeStaffViewModel teachingStaff, Int64 collegeID) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StaffRepository.cs:line 157

Date/Time: 5/3/2020 3:51:08 PM
Error message: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'appContextCentral'.
Inner exception: 
Stack trace:    at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at CEMIS.Business.Central.Repository.Repository`1.CreateAsync(TObject TObject) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\Repository.cs:line 73
   at Cemis.Business.Central.Repository.ActivityLogRepository.CreateActivityLog(String descriptn, String moduleName, String moduleAction, Int64 userid, Object record, String IPAddress) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\ActivityLogRepository.cs:line 36

Date/Time: 5/5/2020 7:19:53 AM
Error message: The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.0 Authentication Required. Learn more at
Inner exception: 
Stack trace:    at System.Net.Mail.MailCommand.CheckResponse(SmtpStatusCode statusCode, String response)
   at System.Net.Mail.MailCommand.EndSend(IAsyncResult result)
   at System.Net.Mail.SendMailAsyncResult.SendMailFromCompleted(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mail.SendMailAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpClient.SendMailCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at CEMIS.Business.Central.Services.MailManagementService.SendWelcomeEmail(String emailadd, String username, String password, String loginurl) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Services\MailManagementService.cs:line 336

Date/Time: 5/5/2020 10:49:28 AM
Error message: The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.0 Authentication Required. Learn more at
Inner exception: 
Stack trace:    at System.Net.Mail.MailCommand.CheckResponse(SmtpStatusCode statusCode, String response)
   at System.Net.Mail.MailCommand.EndSend(IAsyncResult result)
   at System.Net.Mail.SendMailAsyncResult.SendMailFromCompleted(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mail.SendMailAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpClient.SendMailCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at CEMIS.Business.Central.Services.MailManagementService.SendWelcomeEmail(String emailadd, String username, String password, String loginurl) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Services\MailManagementService.cs:line 336

Date/Time: 5/6/2020 3:34:43 AM
Error message: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'appContextCentral'.
Inner exception: 
Stack trace:    at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at CEMIS.Business.Central.Repository.Repository`1.CreateAsync(TObject TObject) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\Repository.cs:line 73
   at Cemis.Business.Central.Repository.ActivityLogRepository.CreateActivityLog(String descriptn, String moduleName, String moduleAction, Int64 userid, Object record, String IPAddress) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\ActivityLogRepository.cs:line 36

Date/Time: 5/7/2020 6:53:45 PM
Error message: Input string was not in a correct format.
Inner exception: 
Stack trace:    at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToByte(IFormatProvider provider)
   at Cemis.Business.Central.Repository.StudentRepository.GetStudentProfile(String studentId) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 530

Date/Time: 5/7/2020 9:31:05 PM
Error message: Input string was not in a correct format.
Inner exception: 
Stack trace:    at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToByte(IFormatProvider provider)
   at Cemis.Business.Central.Repository.StudentRepository.GetStudentProfile(String studentId) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 530

Date/Time: 5/9/2020 1:31:22 AM
Error message: Procedure or function GetStudentResult has too many arguments specified.
Inner exception: 
Stack trace:    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at Cemis.Business.Central.Repository.ResultRepository.GetStudentResult(String studentId, Int32 SessionId, Int32 level, Int32 semester) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\ResultRepository.cs:line 127

Date/Time: 5/9/2020 1:47:12 AM
Error message: Input string was not in a correct format.
Inner exception: 
Stack trace:    at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToByte(IFormatProvider provider)
   at Cemis.Business.Central.Repository.StudentRepository.GetStudentProfile(String studentId) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 530

Date/Time: 5/9/2020 1:53:45 AM
Error message: Input string was not in a correct format.
Inner exception: 
Stack trace:    at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToByte(IFormatProvider provider)
   at Cemis.Business.Central.Repository.StudentRepository.GetStudentProfile(String studentId) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 530

Date/Time: 5/9/2020 2:13:01 AM
Error message: Input string was not in a correct format.
Inner exception: 
Stack trace:    at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToByte(IFormatProvider provider)
   at Cemis.Business.Central.Repository.StudentRepository.GetStudentProfile(String studentId) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 530

Date/Time: 5/9/2020 2:16:42 AM
Error message: Input string was not in a correct format.
Inner exception: 
Stack trace:    at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToByte(IFormatProvider provider)
   at Cemis.Business.Central.Repository.StudentRepository.GetStudentProfile(String studentId) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 530

Date/Time: 5/9/2020 2:19:21 AM
Error message: Input string was not in a correct format.
Inner exception: 
Stack trace:    at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToByte(IFormatProvider provider)
   at Cemis.Business.Central.Repository.StudentRepository.GetStudentProfile(String studentId) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 530

Date/Time: 5/9/2020 2:23:55 AM
Error message: Column 'OtherName' does not belong to table .
Inner exception: 
Stack trace:    at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at Cemis.Business.Central.Repository.StudentRepository.GetStudentProfile(String studentId) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 530

Date/Time: 5/9/2020 2:25:34 AM
Error message: Column 'OtherName' does not belong to table .
Inner exception: 
Stack trace:    at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at Cemis.Business.Central.Repository.StudentRepository.GetStudentProfile(String studentId) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 530

Date/Time: 5/9/2020 2:25:41 AM
Error message: Column 'OtherName' does not belong to table .
Inner exception: 
Stack trace:    at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at Cemis.Business.Central.Repository.StudentRepository.GetStudentProfile(String studentId) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 530

Date/Time: 5/9/2020 2:30:34 AM
Error message: Column 'Program' does not belong to table .
Inner exception: 
Stack trace:    at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at Cemis.Business.Central.Repository.StudentRepository.GetStudentProfile(String studentId) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Repository\StudentRepository.cs:line 530

Date/Time: 6/1/2020 12:04:36 PM
Error message: Failure sending mail.
Inner exception: System.Net.Sockets.SocketException (11001): No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DnsCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
Stack trace:    at CEMIS.Business.Central.Services.MailManagementService.SendWelcomeEmail(String emailadd, String username, String password, String loginurl) in C:\Users\aolatunji\Documents\Azure\CEMIS\Cemis.Business.Central\Services\MailManagementService.cs:line 341

